# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
# Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pipenv
        run: |
          sudo apt install python3-pip && sudo pip3 install pipenv
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install depencencies
        run: pipenv install
      - name: Build the site
        run:  pipenv run python blog.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build directory
          path: 'build'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
